import { MapType, Palette, ThemeId } from "./types";

/**
 * Forty curated cartography themes. Each is a deliberate, cohesive color
 * story (not just a background swap) — tuned so water/roads/buildings read
 * clearly against the background while staying in the same tonal family.
 * Major and minor streets get distinct tones so the road hierarchy reads
 * at a glance, the way an engraved city map does.
 */
export const THEME_PRESETS: Record<ThemeId, Palette> = {
  midnightBlue: {
    background: "#10152B",
    land: "#1B2444",
    water: "#0A0E1F",
    roadsMajor: "#C7CEDE",
    roadsMinor: "#414A63",
    buildings: "#2A3560",
    parks: "#1E3038",
    borders: "#9AA5C4",
    labels: "#EDEFF7",
  },
  warmSand: {
    background: "#F3E9D7",
    land: "#F3E9D7",
    water: "#B7C2C2",
    roadsMajor: "#C68B5C",
    roadsMinor: "#B7A47E",
    buildings: "#E4D0AE",
    parks: "#D8CBA0",
    borders: "#A97C50",
    labels: "#493826",
  },
  copper: {
    background: "#251C16",
    land: "#2D2319",
    water: "#123230",
    roadsMajor: "#C56A3F",
    roadsMinor: "#8A6142",
    buildings: "#4B3726",
    parks: "#354139",
    borders: "#B87333",
    labels: "#F0E2D4",
  },
  emerald: {
    background: "#0E2B22",
    land: "#123B2F",
    water: "#1E5346",
    roadsMajor: "#D4AF37",
    roadsMinor: "#6E8F73",
    buildings: "#1B4536",
    parks: "#2D5D49",
    borders: "#D4AF37",
    labels: "#F2E8C9",
  },
  monochrome: {
    background: "#FFFFFF",
    land: "#FFFFFF",
    water: "#1A1A1A",
    roadsMajor: "#000000",
    roadsMinor: "#7A7A7A",
    buildings: "#E9E9E9",
    parks: "#F3F3F3",
    borders: "#000000",
    labels: "#000000",
  },
  softSlate: {
    background: "#DDE1E4",
    land: "#E7E9EA",
    water: "#93A3AC",
    roadsMajor: "#43505A",
    roadsMinor: "#8D98A0",
    buildings: "#C7CCCF",
    parks: "#B7C2BB",
    borders: "#5D6B74",
    labels: "#26313A",
  },
  folio: {
    background: "#F1EAE0",
    land: "#2B2E33",
    water: "#2E6FE0",
    roadsMajor: "#6B4E8C",
    roadsMinor: "#8F8A82",
    buildings: "#383C42",
    parks: "#748C6B",
    borders: "#B5A692",
    labels: "#211D18",
  },
  daylight: {
    background: "#F7F7F5",
    land: "#EAEAE7",
    water: "#9CC9F0",
    roadsMajor: "#F5A623",
    roadsMinor: "#FFFFFF",
    buildings: "#DDD9D2",
    parks: "#C5E1B8",
    borders: "#C9C9C6",
    labels: "#3C4043",
  },
  nightdrive: {
    background: "#1A1D21",
    land: "#202429",
    water: "#0E2036",
    roadsMajor: "#FFA83D",
    roadsMinor: "#3A3F47",
    buildings: "#2A2E34",
    parks: "#16281F",
    borders: "#454B54",
    labels: "#ECEDEF",
  },
  pastelStudio: {
    background: "#F7F1F5",
    land: "#F1D9E4",
    water: "#6FCBC0",
    roadsMajor: "#FF9E80",
    roadsMinor: "#FFFBF6",
    buildings: "#E8D5DC",
    parks: "#B9E3C6",
    borders: "#D9C2CC",
    labels: "#3B2E35",
  },
  blueprint: {
    background: "#123A66",
    land: "#153F70",
    water: "#0B2A4D",
    roadsMajor: "#F5FCFF",
    roadsMinor: "#8FD6F2",
    buildings: "#1A4470",
    parks: "#1E4C7D",
    borders: "#CFEFFB",
    labels: "#F5FCFF",
  },
  cyberpunk: {
    background: "#0D0B18",
    land: "#151226",
    water: "#05040A",
    roadsMajor: "#FF007F",
    roadsMinor: "#7928CA",
    buildings: "#1F1A3A",
    parks: "#00F5D4",
    borders: "#00F5D4",
    labels: "#F0F0F8",
  },
  nordicFrost: {
    background: "#EAF2F8",
    land: "#E1EBF5",
    water: "#5C8BB0",
    roadsMajor: "#1C3144",
    roadsMinor: "#A2BCE0",
    buildings: "#D1E0EF",
    parks: "#C7DBC5",
    borders: "#497296",
    labels: "#102A43",
  },
  terracotta: {
    background: "#F9EBE0",
    land: "#F4DFD0",
    water: "#7E99A3",
    roadsMajor: "#B85042",
    roadsMinor: "#D69F7E",
    buildings: "#EAD5C3",
    parks: "#A7B299",
    borders: "#9C4135",
    labels: "#4A2810",
  },
  vintageAtlas: {
    background: "#ECE2D0",
    land: "#E2D4B9",
    water: "#9DB4C0",
    roadsMajor: "#8C4A32",
    roadsMinor: "#C2A878",
    buildings: "#D6C4A5",
    parks: "#9FB186",
    borders: "#6F4E37",
    labels: "#2B1E1A",
  },
  tokyoNeon: {
    background: "#181824",
    land: "#1F1F30",
    water: "#0F0F1A",
    roadsMajor: "#00E5FF",
    roadsMinor: "#FF0055",
    buildings: "#28283E",
    parks: "#204035",
    borders: "#00E5FF",
    labels: "#FFFFFF",
  },
  sageForest: {
    background: "#ECEFE6",
    land: "#E2E7DA",
    water: "#9FB3B5",
    roadsMajor: "#4A6B5D",
    roadsMinor: "#8EA89D",
    buildings: "#D3DCD0",
    parks: "#B5C4B1",
    borders: "#3B564A",
    labels: "#1E2C26",
  },
  obsidianGold: {
    background: "#121212",
    land: "#1B1B1B",
    water: "#070707",
    roadsMajor: "#FFD700",
    roadsMinor: "#7A6B1F",
    buildings: "#292929",
    parks: "#202A24",
    borders: "#E6C200",
    labels: "#FFF4B8",
  },
  sunsetMinimal: {
    background: "#FFF4EE",
    land: "#FDEAE1",
    water: "#4D6A80",
    roadsMajor: "#FF6B6B",
    roadsMinor: "#F7B2AD",
    buildings: "#F7DCD3",
    parks: "#F1DAAE",
    borders: "#E05353",
    labels: "#3D232A",
  },
  monochromeDark: {
    background: "#0A0A0A",
    land: "#141414",
    water: "#000000",
    roadsMajor: "#FFFFFF",
    roadsMinor: "#555555",
    buildings: "#222222",
    parks: "#1A1A1A",
    borders: "#888888",
    labels: "#FFFFFF",
  },
  desertOasis: {
    background: "#FAF2E6",
    land: "#F3E4CF",
    water: "#458B94",
    roadsMajor: "#C07D49",
    roadsMinor: "#D9AF86",
    buildings: "#E6D3B8",
    parks: "#809A6F",
    borders: "#945D36",
    labels: "#3D2719",
  },
  deepPlum: {
    background: "#1A111E",
    land: "#231829",
    water: "#0F0A12",
    roadsMajor: "#E087B8",
    roadsMinor: "#5E4268",
    buildings: "#312239",
    parks: "#2A3836",
    borders: "#B55A8C",
    labels: "#FAF0F6",
  },
  sunkenTreasure: {
    background: "#0B1D28",
    land: "#112634",
    water: "#061017",
    roadsMajor: "#34B3A0",
    roadsMinor: "#1D5C58",
    buildings: "#1A3648",
    parks: "#15423B",
    borders: "#49C6B3",
    labels: "#E2F7F4",
  },
  creamyMatcha: {
    background: "#F4F6F0",
    land: "#E9EDE1",
    water: "#A1B5A7",
    roadsMajor: "#5B7065",
    roadsMinor: "#9CB0A4",
    buildings: "#D8E0CF",
    parks: "#7A9A60",
    borders: "#465950",
    labels: "#222E27",
  },
  cherryBlossom: {
    background: "#FAF4F5",
    land: "#F3E7EA",
    water: "#A9C2C9",
    roadsMajor: "#D96B81",
    roadsMinor: "#E6B0BD",
    buildings: "#E5D1D7",
    parks: "#B2D3C2",
    borders: "#BE4B62",
    labels: "#3D1C24",
  },
  volcanicAsh: {
    background: "#1C1B1A",
    land: "#262523",
    water: "#121110",
    roadsMajor: "#FF5500",
    roadsMinor: "#5C4B43",
    buildings: "#363432",
    parks: "#2D332A",
    borders: "#D44400",
    labels: "#F5ECE8",
  },
  royalNavy: {
    background: "#0D1B2A",
    land: "#1B263B",
    water: "#060D17",
    roadsMajor: "#E0A96D",
    roadsMinor: "#415A77",
    buildings: "#26364D",
    parks: "#1E3A3A",
    borders: "#C68B45",
    labels: "#E0E1DD",
  },
  warmOlive: {
    background: "#EAE7DC",
    land: "#DFDBD0",
    water: "#8E9AAF",
    roadsMajor: "#8A7968",
    roadsMinor: "#B0A89E",
    buildings: "#CDC8BC",
    parks: "#7F8C72",
    borders: "#6B5E50",
    labels: "#2B2621",
  },
  synthwave: {
    background: "#160926",
    land: "#200D38",
    water: "#0B0414",
    roadsMajor: "#00F0FF",
    roadsMinor: "#BD00FF",
    buildings: "#331659",
    parks: "#FF0075",
    borders: "#00F0FF",
    labels: "#FFFFFF",
  },
  roseGold: {
    background: "#FDF8F7",
    land: "#F7ECE9",
    water: "#A4B8C4",
    roadsMajor: "#B76E79",
    roadsMinor: "#D8B4B8",
    buildings: "#EAD5D8",
    parks: "#C2D4C3",
    borders: "#9E525D",
    labels: "#4A2E33",
  },
  arcticIce: {
    background: "#F4F9FC",
    land: "#E7F0F7",
    water: "#7FA8C9",
    roadsMajor: "#2C5282",
    roadsMinor: "#90CDF4",
    buildings: "#D3E2EE",
    parks: "#B2D8D8",
    borders: "#1A365D",
    labels: "#0F2B48",
  },
  brutalistConcrete: {
    background: "#D6D6D6",
    land: "#CDCDCD",
    water: "#808080",
    roadsMajor: "#111111",
    roadsMinor: "#666666",
    buildings: "#B8B8B8",
    parks: "#A3A8A0",
    borders: "#000000",
    labels: "#000000",
  },
  duneSpice: {
    background: "#24140E",
    land: "#2E1A12",
    water: "#120905",
    roadsMajor: "#E06D3B",
    roadsMinor: "#874627",
    buildings: "#42261B",
    parks: "#383120",
    borders: "#C25323",
    labels: "#FCEFEA",
  },
  lavenderFog: {
    background: "#F3F0F8",
    land: "#E8E2F2",
    water: "#A1A9C9",
    roadsMajor: "#6C5CE7",
    roadsMinor: "#B4ACE3",
    buildings: "#D7CEE8",
    parks: "#A8CFB8",
    borders: "#5142C4",
    labels: "#2D2652",
  },
  mustardRetro: {
    background: "#F7F0E1",
    land: "#EDE3CE",
    water: "#5C768D",
    roadsMajor: "#D99B26",
    roadsMinor: "#B8A37A",
    buildings: "#DFD2B7",
    parks: "#8A9A66",
    borders: "#B87F14",
    labels: "#362B16",
  },
  matrixGreen: {
    background: "#050B07",
    land: "#0A140E",
    water: "#020503",
    roadsMajor: "#00FF66",
    roadsMinor: "#008837",
    buildings: "#102318",
    parks: "#004D25",
    borders: "#00FF66",
    labels: "#E0FFE9",
  },
  biscuitParchment: {
    background: "#EBE3D5",
    land: "#E0D7C6",
    water: "#9BA4B0",
    roadsMajor: "#635246",
    roadsMinor: "#A6988B",
    buildings: "#D1C5B4",
    parks: "#A3B19B",
    borders: "#4A3B30",
    labels: "#292019",
  },
  electricViolet: {
    background: "#13091F",
    land: "#1C0E2E",
    water: "#09040F",
    roadsMajor: "#9D4EDD",
    roadsMinor: "#5A189A",
    buildings: "#2D1548",
    parks: "#104547",
    borders: "#C77DFF",
    labels: "#F7EFFF",
  },
  subtleClay: {
    background: "#F2EDE9",
    land: "#E8DFD8",
    water: "#9CB0B8",
    roadsMajor: "#A87667",
    roadsMinor: "#C9AEA6",
    buildings: "#DDD0C7",
    parks: "#B4C2B1",
    borders: "#8A594B",
    labels: "#382B27",
  },
  abyssalTrench: {
    background: "#050C1A",
    land: "#0A152B",
    water: "#02060F",
    roadsMajor: "#00B4D8",
    roadsMinor: "#0077B6",
    buildings: "#10203F",
    parks: "#0A2F35",
    borders: "#90E0EF",
    labels: "#CAF0F8",
  },
};

export const THEME_LABELS: Record<ThemeId, string> = {
  midnightBlue: "Midnight Blue",
  warmSand: "Warm Sand",
  copper: "Copper",
  emerald: "Emerald",
  monochrome: "High Contrast Mono",
  softSlate: "Soft Slate",
  folio: "Folio",
  daylight: "Daylight",
  nightdrive: "Nightdrive",
  pastelStudio: "Pastel Studio",
  blueprint: "Blueprint",
  cyberpunk: "Cyberpunk",
  nordicFrost: "Nordic Frost",
  terracotta: "Terracotta",
  vintageAtlas: "Vintage Atlas",
  tokyoNeon: "Tokyo Neon",
  sageForest: "Sage Forest",
  obsidianGold: "Obsidian Gold",
  sunsetMinimal: "Sunset Minimal",
  monochromeDark: "Dark Inverted Mono",
  desertOasis: "Desert Oasis",
  deepPlum: "Deep Plum",
  sunkenTreasure: "Sunken Treasure",
  creamyMatcha: "Creamy Matcha",
  cherryBlossom: "Cherry Blossom",
  volcanicAsh: "Volcanic Ash",
  royalNavy: "Royal Navy",
  warmOlive: "Warm Olive",
  synthwave: "Synthwave",
  roseGold: "Rose Gold",
  arcticIce: "Arctic Ice",
  brutalistConcrete: "Brutalist Concrete",
  duneSpice: "Dune Spice",
  lavenderFog: "Lavender Fog",
  mustardRetro: "Mustard Retro",
  matrixGreen: "Matrix Green",
  biscuitParchment: "Biscuit Parchment",
  electricViolet: "Electric Violet",
  subtleClay: "Subtle Clay",
  abyssalTrench: "Abyssal Trench",
};

export const THEME_DESCRIPTIONS: Record<ThemeId, string> = {
  midnightBlue: "Deep sapphire night with silver moonlit lines.",
  warmSand: "Sun-bleached parchment with terracotta roads.",
  copper: "Espresso brown with etched copper roads.",
  emerald: "Forest green with gilded accents.",
  monochrome: "Pure black and white, maximum contrast.",
  softSlate: "Cool architectural grey, quiet and precise.",
  folio: "Warm paper canvas, the city inked in charcoal.",
  daylight: "Bright, clean wayfinding — the classic day map.",
  nightdrive: "Daylight after dark, with amber highways.",
  pastelStudio: "Soft lavender and teal, a designer's palette.",
  blueprint: "Drafting-table blue with sharp chalk-white lines.",
  cyberpunk: "High-voltage neon pink and cyan against deep dark.",
  nordicFrost: "Icy Scandinavian blues with deep navy accents.",
  terracotta: "Warm Mediterranean clay tones with muted slate water.",
  vintageAtlas: "Aged antiquarian map with sepia and ink details.",
  tokyoNeon: "Electric turquoise and hot magenta on midnight grid.",
  sageForest: "Calming botanical greens and soft grey slate.",
  obsidianGold: "Luxe jet-black background with vibrant metallic gold routes.",
  sunsetMinimal: "Warm peach and coral palette inspired by dusk.",
  monochromeDark: "Deep black background with sharp white line contrast.",
  desertOasis: "Warm sand dunes with deep teal water highlights.",
  deepPlum: "Rich dark purple aesthetic with magenta accents.",
  sunkenTreasure: "Oceanic deep cyan with bright sea-foam linework.",
  creamyMatcha: "Soft earthy green tones on a creamy off-white backdrop.",
  cherryBlossom: "Delicate pink and soft rose with slate blue rivers.",
  volcanicAsh: "Dark basalt obsidian contrasted with fiery orange arteries.",
  royalNavy: "Classic nautical deep blue paired with warm brass tones.",
  warmOlive: "Muted botanical earth tones with warm stone neutrals.",
  synthwave: "Retro 80s neon purple grid with cyan and magenta accents.",
  roseGold: "Soft metallic rose blush with sophisticated warm contrast.",
  arcticIce: "Glacial pale ice blue tones with crisp dark indigo hierarchy.",
  brutalistConcrete: "Raw architectural grey tones with bold stark lines.",
  duneSpice: "Rich terracotta brown with fiery amber desert highways.",
  lavenderFog: "Dreamy pastel violet background with deep purple roads.",
  mustardRetro: "70s inspired warm mustard gold with muted slate blue.",
  matrixGreen: "Terminal cyber green linework on deep black void.",
  biscuitParchment: "Tactile natural canvas with rich warm brown ink.",
  electricViolet: "Deep violet night sky with glowing purple arterial roads.",
  subtleClay: "Soft terracotta clay palette with muted slate water.",
  abyssalTrench: "Deep ocean trench blue illuminated by cyan linework.",
};

export const THEME_IDS: ThemeId[] = [
  "midnightBlue",
  "warmSand",
  "copper",
  "emerald",
  "monochrome",
  "softSlate",
  "folio",
  "daylight",
  "nightdrive",
  "pastelStudio",
  "blueprint",
  "cyberpunk",
  "nordicFrost",
  "terracotta",
  "vintageAtlas",
  "tokyoNeon",
  "sageForest",
  "obsidianGold",
  "sunsetMinimal",
  "monochromeDark",
  "desertOasis",
  "deepPlum",
  "sunkenTreasure",
  "creamyMatcha",
  "cherryBlossom",
  "volcanicAsh",
  "royalNavy",
  "warmOlive",
  "synthwave",
  "roseGold",
  "arcticIce",
  "brutalistConcrete",
  "duneSpice",
  "lavenderFog",
  "mustardRetro",
  "matrixGreen",
  "biscuitParchment",
  "electricViolet",
  "subtleClay",
  "abyssalTrench",
];

/** Satellite/terrain are raster imagery — colors are fixed by the source,
 *  but background/labels still drive the poster mat, marker, and type
 *  contrast, so we keep a sensible default palette for each. Road colors
 *  are unused in raster mode (no vector road layer to tint) but still
 *  populated to satisfy the Palette shape. */
export const RASTER_PALETTES: Record<"satellite" | "terrain", Palette> = {
  satellite: {
    background: "#1A1A1A",
    land: "#1A1A1A",
    water: "#123249",
    roadsMajor: "#E8E4D8",
    roadsMinor: "#B8B2A0",
    buildings: "#E8E4D8",
    parks: "#3F5C3F",
    borders: "#F5F1E6",
    labels: "#F5F1E6",
  },
  terrain: {
    background: "#EFE7D8",
    land: "#EFE7D8",
    water: "#A9C6D6",
    roadsMajor: "#B0562F",
    roadsMinor: "#8C6A4E",
    buildings: "#C9BBA3",
    parks: "#9CB380",
    borders: "#6B5A44",
    labels: "#3A2E1F",
  },
};

export const MAP_TYPE_LABELS: Record<MapType, string> = {
  cartography: "Cartography",
  satellite: "Satellite",
  terrain: "Terrain",
};

export function defaultPaletteForMapType(mapType: MapType, theme: ThemeId): Palette {
  if (mapType === "cartography") return THEME_PRESETS[theme];
  return RASTER_PALETTES[mapType];
}
